import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import { once } from 'node:events';
import type { AddressInfo } from 'node:net';
import type { Request, Response, Router, RequestHandler } from 'express';
import { OpenAiCompatibleClient } from '../src/ai/openai-compatible-client';
import { SecretBox } from '../src/ai/secret-box';
import { StateTaskRunner } from '../src/ai/state-task-runner';
import { SnapshotContextProvider } from '../src/ai/snapshot-context-provider';
import { AiConfigStore } from '../src/storage/ai-config-store';
import { StateChainStore } from '../src/storage/state-chain-store';
import { StateTaskStore } from '../src/storage/state-task-store';
import { StateChainEngine } from '../src/state/chain-engine';
import { SqliteStore } from '../src/storage/sqlite-store';
import { SqliteDatabase } from '../src/storage/sqlite-database';
import { ensureStorageDirectories, resolveStoragePaths } from '../src/storage/data-directory';
import { runMigrations } from '../src/storage/migrations';
import { LongMemoryStore } from '../src/storage/long-memory-store';
import { LongMemoryGenerator, type LongMemoryBatchInput } from '../src/memory/long-memory';
import { Bm25SearchService } from '../src/memory/bm25';
import { EmbeddingSearchService } from '../src/memory/embedding';
import { RecallService } from '../src/memory/recall';
import { packMemories } from '../src/memory/token-packer';
import { MemoryRuntime } from '../src/core/runtime';
import { PerChatQueue } from '../src/queue/per-chat-queue';
import { registerAiRoutes } from '../src/api/ai-routes';
import { registerMemoryRoutes } from '../src/api/memory-routes';
import { registerStateRoutes } from '../src/api/state-routes';
import { registerRoutes } from '../src/api/routes';
import { LongMemoryScheduler } from '../src/memory/long-memory-scheduler';
import { fingerprint, dependencyFingerprint } from '../src/core/fingerprint';
import { STATE_PROTOCOL_VERSION } from '../src/protocol';
import { STATE_SCHEMA_VERSION } from '../src/state/schema';

async function main() {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'wm-phase16-api-'));
  (globalThis as typeof globalThis & { DATA_ROOT: string }).DATA_ROOT = root;
  const paths = resolveStoragePaths();
  await ensureStorageDirectories(paths);
  const db = await SqliteDatabase.open(paths.databasePath);
  const requests: string[] = [];
  const mock = http.createServer(async (req, res) => {
    let body = ''; for await (const chunk of req) body += String(chunk);
    requests.push(body);
    res.setHeader('content-type', 'application/json');
    if (req.url?.endsWith('/models')) { res.end(JSON.stringify({ data: [{ id: 'test-model' }] })); return; }
    if (req.url?.endsWith('/embeddings')) { res.end(JSON.stringify({ model: 'test-model', data: [{ index: 0, embedding: [1, 0, 0] }] })); return; }
    const output = body.includes('[LongMemoryBatchInput]') ? { slices: [{ startFloor: 1, endFloor: 1, summary: 'Alice found the ancient key', tags: ['key'], characterIds: ['alice'], plotlineIds: ['quest'] }] } : {};
    res.end(JSON.stringify({ model: 'test-model', choices: [{ message: { content: JSON.stringify(output) }, finish_reason: 'stop' }] }));
  });
  mock.listen(0, '127.0.0.1'); await once(mock, 'listening');
  let runner: StateTaskRunner | undefined;
  try {
    await runMigrations(db, paths);
    const config = new AiConfigStore(db, await SecretBox.load(paths.secretKeyPath)); await config.ensureBuiltinPresets();
    const client = new OpenAiCompatibleClient(), memories = new LongMemoryStore(db), store = new SqliteStore(db), nodes = new StateChainStore(db);
    const queue = new PerChatQueue();
    const chain = new StateChainEngine({ database: db, chain: nodes, store, checkpointInterval: async () => 20, promptVersion: async () => (await config.getActivePrompt('state')).promptVersion });
    const tasks = new StateTaskStore(db);
    runner = new StateTaskRunner({ store, tasks, aiConfig: config, client, queue, chain, context: new SnapshotContextProvider(chain, tasks) });
    const generator = new LongMemoryGenerator({ aiConfig: config, client, store: memories });
    const scheduler = new LongMemoryScheduler({ store, chain: nodes, memories, generator, synchronize: async (chatId, branchId) => { await chain.syncStatuses(await chain.trustedPrefix(chatId, branchId)); } });
    const bm25 = new Bm25SearchService(memories), embedding = new EmbeddingSearchService(memories, config, client);
    const recall = new RecallService(bm25, embedding, config, client);
    const runtime = new MemoryRuntime(store, queue, runner, chain, recall, memories, config);
    const handlers = new Map<string, RequestHandler>();
    const register = (method: string) => (url: string, ...callbacks: RequestHandler[]) => { handlers.set(method + url, callbacks.at(-1)!); };
    const router = { get: register('GET'), post: register('POST') } as unknown as Router;
    registerAiRoutes(router, { aiConfig: config, client, stateTasks: runner, summaryGenerator: generator });
    registerMemoryRoutes(router, { generator, store: memories, bm25, embedding, recall, aiConfig: config, scheduler });
    registerStateRoutes(router, { stateTasks: runner, chain, store });
    registerRoutes(router, runtime, db);
    const call = async (method: string, url: string, body: Record<string, unknown> = {}, expectedStatus = 200): Promise<Record<string, unknown>> => {
      let status = 200, payload: Record<string, unknown> = {};
      const res = { status(code: number) { status = code; return res; }, json(value: Record<string, unknown>) { payload = value; } };
      await handlers.get(method + url)!({ body, query: body } as unknown as Request, res as unknown as Response, () => undefined);
      assert.equal(status, expectedStatus, JSON.stringify(payload)); return payload;
    };
    const baseUrl = `http://127.0.0.1:${(mock.address() as AddressInfo).port}/v1`;
    const channel = (await call('POST', '/ai/channels/save', { name: 'test', baseUrl, apiType: 'openai-compatible', apiKey: 'first' })).channel as { channelId: string; hasApiKey: boolean };
    assert.ok(channel.channelId); assert.equal(channel.hasApiKey, true); assert.equal('apiKey' in channel, false);
    await call('POST', '/ai/channels/save', { channelId: channel.channelId, name: 'changed', baseUrl });
    assert.equal((await config.getChannel(channel.channelId))!.apiKey, 'first');
    await call('POST', '/ai/channels/save', { channelId: channel.channelId, name: 'changed', baseUrl, apiKey: 'second' });
    assert.equal((await config.getChannel(channel.channelId))!.apiKey, 'second');
    await call('POST', '/ai/channels/save', { channelId: channel.channelId, name: 'changed', baseUrl, apiKey: null });
    assert.equal((await config.getChannel(channel.channelId))!.apiKey, null);
    assert.deepEqual((await call('POST', '/ai/channels/models', { channelId: channel.channelId })).models, ['test-model']);
    const probe = await call('POST', '/ai/channels/test', { channelId: channel.channelId });
    assert.equal(probe.ok, true); assert.equal(probe.modelCount, 1); assert.equal(typeof probe.durationMs, 'number'); assert.equal('latencyMs' in probe, false);
    const roles = ['summary', 'state', 'embedding', 'rerank'] as const;
    for (const role of roles) await call('POST', '/ai/model-bindings/save', { role, channelId: channel.channelId, model: 'test-model' });
    for (const role of roles) assert.equal((await config.getBindings())[role]!.channelId, channel.channelId);
    for (const role of roles) {
      const separate = await config.saveChannel({ name: role, baseUrl });
      await call('POST', '/ai/model-bindings/save', { role, channelId: separate.channelId, model: 'test-model' });
    }
    assert.equal(new Set(Object.values(await config.getBindings()).map(binding => binding!.channelId)).size, 4);
    await call('POST', '/ai/model-bindings/save', { role: 'rerank', channelId: null }); assert.equal((await config.getBindings()).rerank, null);
    await call('POST', '/ai/model-bindings/save', { role: 'rerank', channelId: channel.channelId, model: 'test-model' });
    await call('POST', '/ai/channels/delete', { channelId: channel.channelId }); assert.equal((await config.getBindings()).rerank, null);
    for (const promptType of ['state', 'summary'] as const) {
      const list = await call('GET', '/ai/prompts', { type: promptType }); assert.equal(list.activePresetId, `builtin:${promptType}`);
      const content = { system: `${promptType} custom test marker`, task: 'Analyze the supplied text.' };
      const preset = (await call('POST', '/ai/prompts/save', { promptType, name: 'custom', content })).preset as { presetId: string; version: number };
      assert.equal(preset.version, 1);
      const updated = (await call('POST', '/ai/prompts/save', { presetId: preset.presetId, promptType, name: 'updated', content })).preset as { version: number };
      assert.equal(updated.version, 2);
      await call('POST', '/ai/prompts/activate', { promptType, presetId: preset.presetId });
      const tested = await call('POST', '/ai/prompts/test', { promptType, sampleContent: 'Alice found the ancient key' });
      assert.equal(tested.ok, true); assert.ok(tested.result); assert.equal(typeof tested.durationMs, 'number'); assert.equal(typeof tested.promptVersion, 'string');
      assert.equal((await memories.list('prompt-test', 'prompt-test', true)).length, 0);
      assert.ok(requests.some(request => request.includes(content.system)));
      await call('POST', '/ai/prompts/save', { promptType, presetId: `builtin:${promptType}`, name: 'illegal', content }, 400);
      await call('POST', '/ai/prompts/reset', { promptType });
      await call('POST', '/ai/prompts/delete', { presetId: preset.presetId });
    }
    const input: LongMemoryBatchInput = { chatId: 'c', branchId: 'b', batchStartFloor: 1, batchEndFloor: 1, floors: [{ floorId: 'f1', content: 'Alice found the ancient key' }], stateDeltas: [], endStateDigest: { stateNodeId: 'n1', stateFingerprint: 'fp' } };
    const original = await generator.generate(input);
    await call('POST', '/memory/toggle-active', { memoryId: original[0].memoryId, stale: true });
    assert.equal(((await call('GET', '/memory/list', { chatId: 'c', branchId: 'b' })).memories as unknown[]).length, 0);
    assert.equal(((await call('GET', '/memory/list', { chatId: 'c', branchId: 'b', includeStale: 'true' })).memories as unknown[]).length, 1);
    await bm25.search('c', 'b', 'ancient key', 10); await embedding.search('c', 'b', 'key', 10);
    await call('POST', '/memory/toggle-active', { memoryId: original[0].memoryId, stale: false });
    assert.equal((await bm25.search('c', 'b', 'ancient key', 10)).length, 1);
    assert.equal((await embedding.search('c', 'b', 'key', 10)).length, 1);
    const active = (await memories.list('c', 'b'))[0]; assert.equal(active.bm25Indexed, true); assert.equal(active.embeddingIndexed, true);
    await call('POST', '/memory/toggle-active', { memoryId: active.memoryId, stale: true });
    await call('POST', '/memory/toggle-active', { memoryId: active.memoryId, stale: false });
    assert.equal((await embedding.search('c', 'b', 'key', 10)).length, 1);
    assert.equal((await memories.list('c', 'b'))[0].embeddingIndexed, true, 'reactivation restores flag even without an intervening sync');
    const custom = await config.savePreset({ promptType: 'summary', name: 'New summary', content: { system: 'new summary generation marker', task: 'Summarize.' } });
    await config.activatePreset('summary', custom.presetId);
    assert.equal((await memories.list('c', 'b')).length, 0, 'old prompt memories are excluded immediately');
    await call('POST', '/memory/toggle-active', { memoryId: original[0].memoryId, stale: false }, 400);
    const regenerated = await generator.generate(input);
    assert.notEqual(regenerated[0].batchDependencyFingerprint, original[0].batchDependencyFingerprint);
    assert.ok(requests.at(-1)!.includes('new summary generation marker'));
    await call('POST', '/ai/settings/save', { longMemory: { latestForcedCount: 4 }, recall: { tokenRatio: 0.05, minTokenBudget: 100, maxTokenBudget: 300 } });
    const reloaded = new AiConfigStore(db, await SecretBox.load(paths.secretKeyPath));
    assert.equal((await reloaded.getLongMemorySettings()).latestForcedCount, 4);
    const savedRecall = await reloaded.getRecallSettings();
    assert.equal(savedRecall.tokenRatio, 0.05); assert.equal(savedRecall.minTokenBudget, 100); assert.equal(savedRecall.maxTokenBudget, 300);
    assert.equal(packMemories({ recallCandidates: [], fixedRecentMemories: [] }, { contextWindow: 4000, ...savedRecall }).tokenLimit, 200);
    await call('POST', '/ai/settings/save', { recall: { minTokenBudget: 1000, maxTokenBudget: 10 } }, 400);
    await call('POST', '/ai/settings/save', { recall: { minTokenBudget: 100.5 } }, 400);
    const debug = await call('POST', '/recall/debug', { chatId: 'c', branchId: 'b', query: 'ancient key', contextWindow: 4000 });
    for (const key of ['bm25', 'embedding', 'rrf', 'rerank', 'final', 'errors', 'pack', 'timings']) assert.ok(key in debug);
    assert.equal((debug.pack as { tokenLimit: number }).tokenLimit, 200); assert.equal('candidates' in debug, false);
    const diagnostics = await call('GET', '/debug/current', { chatId: 'c', branchId: 'b' });
    assert.equal((diagnostics.database as { available: boolean }).available, true); assert.equal(diagnostics.stateTask, null); assert.ok(diagnostics.summary);
    await call('POST', '/state/manual-edit', { chatId: 'c', branchId: 'b', target: 'invalid' }, 400);
    await call('POST', '/state/manual-edit', { chatId: 'c', branchId: 'b', target: 'profile', action: 'invalid' }, 400);
    const rangeChat = 'range-api';
    const rangeBranch = await store.getOrCreateActiveBranch(rangeChat);
    const floors = await store.reconcileChat({ chatId: rangeChat, branchId: rangeBranch, floors: [{ messageIndex: 0, swipeId: 0, content: 'server source marker: Alice found a key' }] });
    const floor = (await store.getFloor(floors.activeFloorIds[0]))!;
    const promptVersion = (await config.getActivePrompt('state')).promptVersion;
    await chain.commitCandidate({ chatId: rangeChat, branchId: rangeBranch, hostChatId: rangeChat, floorId: floor.floorKey, messageIndex: 0, swipeId: 0, bodyFingerprint: fingerprint(floor.content), dependencyFingerprint: dependencyFingerprint({ bodyFingerprint: fingerprint(floor.content), previousStateFingerprint: null, protocolVersion: STATE_PROTOCOL_VERSION, schemaVersion: STATE_SCHEMA_VERSION, promptVersion }), candidate: {}, previous: null });
    const rangeResult = await call('POST', '/memory/resummarize-range', { chatId: rangeChat, branchId: rangeBranch, startFloor: 1, endFloor: 1 });
    const rangeMemories = rangeResult.memories as Array<{ batchId: string; sourceFloorIds: string[] }>;
    assert.deepEqual(rangeMemories[0].sourceFloorIds, [floor.floorKey]);
    assert.ok(requests.at(-1)!.includes('server source marker'));
    const repeated = await call('POST', '/memory/resummarize-range', { chatId: rangeChat, branchId: rangeBranch, batchId: rangeMemories[0].batchId });
    assert.notEqual((repeated.memories as Array<{ batchId: string }>)[0].batchId, rangeMemories[0].batchId);
    assert.equal(((await call('GET', '/memory/list', { chatId: rangeChat, branchId: rangeBranch })).memories as unknown[]).length, 1);
    assert.equal(((await call('GET', '/memory/list', { chatId: rangeChat, branchId: rangeBranch, includeStale: 'true' })).memories as unknown[]).length, 2);
    await call('POST', '/state/manual-edit', { chatId: rangeChat, branchId: rangeBranch, target: 'story', fieldPath: 'calendar', value: [{ id: 'bad', title: 'missing schema fields' }] }, 400);
    await call('POST', '/state/manual-edit', { chatId: rangeChat, branchId: rangeBranch, target: 'story', fieldPath: 'now.currentTime', value: 'day two' });
    assert.equal((await chain.current(rangeChat, rangeBranch)).snapshot.story.now.currentTime, 'day two', 'queue continues after rejected schema');
    const validHead = (await chain.trustedPrefix(rangeChat, rangeBranch)).head!;
    const expanded = await store.reconcileChat({ chatId: rangeChat, branchId: rangeBranch, floors: [{ messageIndex: 0, swipeId: 0, content: floor.content }, { messageIndex: 1, swipeId: 0, content: 'edited next floor' }] });
    const second = (await store.getFloor(expanded.activeFloorIds[1]))!;
    const oldBody = fingerprint('old next floor');
    await chain.commitCandidate({ chatId: rangeChat, branchId: rangeBranch, hostChatId: rangeChat, floorId: second.floorKey, messageIndex: 1, swipeId: 0, bodyFingerprint: oldBody, dependencyFingerprint: dependencyFingerprint({ bodyFingerprint: oldBody, previousStateFingerprint: validHead.stateFingerprint, protocolVersion: STATE_PROTOCOL_VERSION, schemaVersion: STATE_SCHEMA_VERSION, promptVersion }), candidate: { story: { now: { currentTime: 'stale future' } } }, previous: validHead });
    const displayed = await call('GET', '/state/current', { chatId: rangeChat, branchId: rangeBranch });
    assert.equal(displayed.stateNodeId, validHead.stateNodeId, 'UI and manual edit use the same valid state base');
    console.log('Phase 16 API and summary prompt acceptance passed');
  } finally { await runner?.shutdown(); await db.close(); mock.close(); await fs.rm(root, { recursive: true, force: true }); }
}
void main().catch(error => { console.error(error); process.exitCode = 1; });
